auctions/urls.py
from django.conf.urls import url
from .views import (Current_Player_Data,Auction,Unsold_Player_Data,Refresh_Player_Data,
                    Sold_Player_Data,Team_Money,Top_Sold_Player_Data,Start_Auction,
                    Skip_Player,Sell_Player)
urlpatterns = [
    url(r'^current_player/$', Current_Player_Data.as_view()),
    url(r'^unsold_players/$', Unsold_Player_Data.as_view()),
    url(r'^refresh_players/$', Refresh_Player_Data.as_view()),
    url(r'^sold_players/$', Sold_Player_Data.as_view()),
    url(r'^top_sold_players/$', Top_Sold_Player_Data.as_view()),
    url(r'^team_money/$', Team_Money.as_view()),
    url(r'^start_auction/$', Start_Auction.as_view()),
    url(r'^skip_player/$', Skip_Player.as_view()),
    url(r'^sell_player/$', Sell_Player.as_view()),
    url(r'^$', Auction.as_view(),name='auctions'),
]

kpl/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^kpl/admin/', admin.site.urls),
    url(r'^kpl/', include('dashboard.urls')),
    url(r'^kpl/auction/', include('auctions.urls')),
    url(r'^kpl/teams/', include('teams.urls',namespace='teams')),
    url(r'^kpl/match/', include('matches.urls',namespace='match')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matches/urls.py
from django.conf.urls import url
from .views import (Match_Display,New_Match,New_Over,New_Ball,Bold_Wicket,Caught_Wicket,Runout_Wicket,Stumped_Wicket,
                    Hit_Wicket,First_Over,Female_Over,End_First_Innings,Retire_Player,End_Match,Clear_Stats)

urlpatterns = [
    url(r'^schedule/$', Match_Display.as_view(),name='schedule'),
    url(r'^new_match/$', New_Match.as_view(),name='new_match'),
    url(r'^first_over/$', First_Over.as_view(),name='first_over'),
    url(r'^new_over/$', New_Over.as_view(),name='new_over'),
    url(r'^female_over/$', Female_Over.as_view(),name='female_over'),
    url(r'^new_ball/$', New_Ball.as_view(),name='new_ball'),
    url(r'^wicket_bold/$', Bold_Wicket.as_view(),name='bold_wicket'),
    url(r'^wicket_caught/$', Caught_Wicket.as_view(),name='caught_wicket'),
    url(r'^wicket_runout/$', Runout_Wicket.as_view(),name='runout_wicket'),
    url(r'^wicket_stumped/$', Stumped_Wicket.as_view(),name='stumped_wicket'),
    url(r'^wicket_hit/$', Hit_Wicket.as_view(),name='hit_wicket'),
    url(r'^retire_player/$', Retire_Player.as_view(),name='retire_player'),
    url(r'^end_first_inning/$', End_First_Innings.as_view(),name='end_first_inning'),
    url(r'^end_match/$', End_Match.as_view(),name='end_match'),
    url(r'^clear_stats/$', Clear_Stats.as_view(),name='clear_stats'),
]

teams/urls.py
from django.conf.urls import url
from .views import Team_Display,Team_Players

urlpatterns = [
    url(r'^$', Team_Display.as_view(),name='display'),
    url(r'^players/(?P<pk>[0-9]+)/', Team_Players.as_view(),name='players'),
]

auctions/models.py
from __future__ import unicode_literals

from django.db import models
from players.models import Player
from teams.models import Team
# Create your models here.
class Refresh_Data(models.Model):
    refresh = models.CharField(max_length=1,default='0')
class Current_Player(models.Model):
    current_player = models.ForeignKey(Player,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.current_player)

class Sold_Player(models.Model):
    player = models.ForeignKey(Player,on_delete=models.CASCADE)
    team = models.ForeignKey(Team,on_delete=models.CASCADE)
    price = models.IntegerField(default=0)
    runs = models.IntegerField(default=0)
    wickets = models.IntegerField(default=0)
    balls = models.IntegerField(default=0)
    sixes = models.IntegerField(default=0)
    fours = models.IntegerField(default=0)
    catches = models.IntegerField(default=0)
    runout = models.IntegerField(default=0)

    def __str__(self):
        return str(self.player)

players/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Player(models.Model):
    cat_opts = (
        ('Batsman', 'Batsman'),
        ('Bowler', 'Bowler'),
        ('All-Rounder', 'All-Rounder'),
    )
    year_opts = (
        ('First', 'First'),
        ('Second', 'Second'),
        ('Third', 'Third'),
    )
    pool_opts = (
        ('A', 'A'),
        ('B', 'B'),
    )
    manager_opts = (
        ('Yes', 'Yes'),
        ('No', 'No'),
    )
    gender_opts = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    auction_opts = (
        ('pending', 'pending'),
        ('sold', 'sold'),
    )
    name = models.CharField(max_length=100, unique=True)
    gender = models.CharField(choices=gender_opts,default='Male',max_length=6)
    manager = models.CharField(choices=manager_opts,max_length=3)
    year = models.CharField(max_length=10,choices=year_opts)
    pic = models.ImageField(upload_to='player_pics/')
    phone_no = models.CharField(max_length=10)
    category = models.CharField(choices=cat_opts, max_length=100)
    prev_exp = models.TextField(max_length=100,default='Not Specified')
    kpl_exp = models.TextField(max_length=100,default='None')
    pool = models.CharField(max_length=1,choices=pool_opts,default='B')
    auction_status = models.CharField(choices=auction_opts,max_length=10,default='pending')
    class Meta:
        ordering = ['pool','name']
    def __str__(self):
        return str(self.name)

teams/models.py
from __future__ import unicode_literals

from django.db import models
from players.models import Player
# Create your models here.


class Team(models.Model):
    manager_only_opts = (
        ('Yes', 'Yes'),
        ('No', 'No'),
    )
    name = models.CharField(max_length=50)
    manager = models.ForeignKey(Player,on_delete=models.CASCADE)
    captain = models.ForeignKey(Player,on_delete=models.CASCADE,related_name='captain')
    logo = models.ImageField(upload_to='team_logo/')
    manager_only = models.CharField(choices=manager_only_opts,max_length=3,default='No')
    players_cost = models.IntegerField(default=0)
    manager_cost = models.IntegerField(default=0)
    money = models.IntegerField(default=3000)
    alias = models.CharField(max_length=10,blank=True)
    def __str__(self):
        return str(self.name)

auctions/forms.py
from django.forms import ModelForm
from .models import Sold_Player,Current_Player

class Player_Auction_Form(ModelForm):
    class Meta:
        exclude = ['player']
        model = Sold_Player

players/forms.py
from django.forms import ModelForm
from .models import Player


class PlayerForm(ModelForm):
    class Meta:
        exclude = ['pool']
        model = Player
        labels = {
            'name': 'Full Name',
            'phone_no': 'Phone Number',
            'pic': 'Profile Picture (Provide a picture where face is clearly visible)',
            'prev_exp': 'Previous Cricket Experience',
            'kpl_exp': 'Previous KPL Experience',
            'manager':'Want to be a Team Manager?'
        }

auctions/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.models import User
from rest_framework.response import Response
from rest_framework.views import APIView
from players.models import Player
from teams.models import Team
from .serializers import Current_Player_Serializer,Unsold_Player_Serializer,Refresh_Data_Serializer,Sold_Player_Serializer,Team_Serializer
from .models import Current_Player,Refresh_Data,Sold_Player
from .forms import Player_Auction_Form
from django.http import HttpResponseRedirect
import random
# Create your views here.

class Auction(View):
    def get(self,request):
        player_form = Player_Auction_Form()
        admin = User.objects.get(username='raj')
        context={
            'player_form':player_form,
            'admin':admin
        }
        return render(request,"auction.html",context)
class Start_Auction(View):
    def get(self,request):
        if request.user.username =='raj':
            players = Player.objects.all()
            for player in players:
                player.auction_status = 'pending'
                player.save()
            teams = Team.objects.all()
            for team in teams:
                team.players_cost = 0
                team.manager_cost = 0
                team.money = 3000
                team.save()
            players = Player.objects.filter(auction_status='pending',pool='A').exclude(gender='Female').exclude(manager='Yes')
            tot = len(players)
            player = players[random.randint(0,tot-1)]
            Sold_Player.objects.all().delete()
            Current_Player.objects.all().delete()
            current_player = Current_Player(current_player=player)
            current_player.save()
            refresh = Refresh_Data.objects.get(id=1)
            if refresh.refresh == '0':
                refresh.refresh = '1'
            else:
                refresh.refresh = '0'
            refresh.save()
        return HttpResponseRedirect('/kpl/auction/')
class Skip_Player(View):
    def get(self, request):
        players = Player.objects.filter(auction_status='pending', pool='A').exclude(gender='Female').exclude(manager='Yes')
        tot = len(players)
        if tot>0:
            player = players[random.randint(0, tot - 1)]
        else:
            players = Player.objects.filter(auction_status='pending', pool='B').exclude(gender='Female').exclude(manager='Yes')
            tot = len(players)
            player = players[random.randint(0, tot - 1)]
        current_player = Current_Player.objects.all()
        current_player[0].delete()
        cur_player = Current_Player(current_player=player)
        cur_player.save()
        refresh = Refresh_Data.objects.get(id=1)
        if refresh.refresh == '0':
            refresh.refresh = '1'
        else:
            refresh.refresh = '0'
        refresh.save()
        return HttpResponseRedirect('/kpl/auction/')
class Sell_Player(View):
    def post(self,request):
        try:
            player = Current_Player.objects.all()[0]
            team = Team.objects.get(id=request.POST['team'])
            price = int(request.POST['price'])
            sold_player = Sold_Player(player=player.current_player,team=team,price=price)
            sold_player.save()
            player.current_player.auction_status = 'sold'
            player.current_player.save()
            team.players_cost+=price
            costliest_player = Sold_Player.objects.filter(team=team).order_by('-price')[0]
            if team.manager_only=='No':
                team.manager_cost = 0.75*costliest_player.price
            team.money = 3000-(team.players_cost+team.manager_cost)
            team.save()
            refresh = Refresh_Data.objects.get(id=1)
            players = Player.objects.filter(auction_status='pending', pool='A').exclude(gender='Female').exclude(manager='Yes')
            tot = len(players)
            if tot > 0:
                player = players[random.randint(0, tot - 1)]
            else:
                players = Player.objects.filter(auction_status='pending', pool='B').exclude(gender='Female').exclude(manager='Yes')
                tot = len(players)
                player = players[random.randint(0, tot - 1)]
            Current_Player.objects.all().delete()
            cur_player = Current_Player(current_player=player)
            cur_player.save()
            if refresh.refresh == '0':
                refresh.refresh = '1'
            else:
                refresh.refresh = '0'
            refresh.save()
        except:
            Current_Player.objects.all().delete()
            refresh = Refresh_Data.objects.get(id=1)
            if refresh.refresh == '0':
                refresh.refresh = '1'
            else:
                refresh.refresh = '0'
            refresh.save()
        return HttpResponseRedirect('/kpl/auction/')
class Current_Player_Data(APIView):
    def get(self,request):
        player = Current_Player.objects.all()[0]
        player_obj = Current_Player_Serializer(player.current_player)
        return Response({'current_player':player_obj.data},status=200)
class Unsold_Player_Data(APIView):
    def get(self,request):
        players = Player.objects.filter(auction_status='pending').exclude(gender='Female').exclude(manager='Yes').order_by('pool','name')
        player_obj = Unsold_Player_Serializer(players,many=True)
        return Response(data=player_obj.data,status=200)
class Sold_Player_Data(APIView):
    def get(self,request):
        sold_players = Sold_Player.objects.all().exclude(player__gender='Female').order_by('-id')
        sold_player_obj = Sold_Player_Serializer(sold_players,many=True)
        return Response(data=sold_player_obj.data,status=200)
class Top_Sold_Player_Data(APIView):
    def get(self,request):
        top_sold_players = Sold_Player.objects.all().exclude(player__gender='Female').order_by('-price')[:8]
        top_sold_player_obj = Sold_Player_Serializer(top_sold_players,many=True)
        return Response(data=top_sold_player_obj.data,status=200)
class Refresh_Player_Data(APIView):
    def get(self,request):
        refresh = Refresh_Data.objects.all()[0]
        refresh_obj = Refresh_Data_Serializer(refresh)
        return Response({'refresh':refresh_obj.data},status=200)

class Team_Money(APIView):
    def get(self,request):
        teams = Team.objects.all().order_by('-money','name')
        team_obj = Team_Serializer(teams,many=True)
        return Response(data=team_obj.data, status=200)

teams/views.py
from django.shortcuts import render
from django.views import View
from .models import Team
from auctions.models import Sold_Player
# Create your views here.


class Team_Display(View):
    def get(self,request):
        teams = Team.objects.all()
        context = {
            'teams':teams
        }
        return render(request,'teams.html',context)

class Team_Players(View):
    def get(self,request,pk):
        team = Team.objects.get(pk=pk)
        manager = team.manager
        players = Sold_Player.objects.filter(team=team).order_by('player__name')
        context = {
            'team':team,
            'manager':manager,
            'players':players,
        }
        return render(request,'team_players.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>KPL 2017</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


    <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static "css/mytheme.css" %}"/>


    <!-- Custom Fonts -->
    <link href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic"
          rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static "vendor/magnific-popup/magnific-popup.css" %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static "css/AdminLTE.css" %}" rel="stylesheet">
    <link href="{% static "css/creative.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="{% static "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"%}"></script>
        <script src="{% static "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"%}"></script>
    <![endif]-->


</head>

<body id="page-top">

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" style="font-size: 14px;" href="{% url 'home' %}">Kresit Premier League 2017</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
        ">
        <ul class="nav navbar-nav navbar-right">
            {% ifequal user 'raj' %}
                <li>
                <a style="color:black;" class="page-scroll" href="{% url 'match:new_match' %}">Scoring</a>
            </li>
            {% endifequal %}
            <li>
                <a style="color:black;" class="page-scroll" href="{% url 'match:schedule' %}">Schedule</a>
            </li>
            <li>
                <a style="color:black;" class="page-scroll" href="{% url 'teams:display' %}">Teams</a>
            </li>
            <li>
                <a style="color:black;" class="page-scroll" href="{% url 'players' %}">Players</a>
            </li>
            <li>
                <a style="color:black;" class="page-scroll" href="{% url 'rules' %}">Rules</a>
            </li>
            <li>
                <a style="color:black;" class="page-scroll" href="{% url 'organizers' %}">Organizers</a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

{% block content %}
{% endblock %}

<section id=" contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">KRESIT Premier League Season 9!</h2>
                <hr class="primary">
                <p>KPL ( KreSIT Premier League) is the annual cricket tournament exclusive for Postgraduate students of Computer Science and Engineering Department, IITB.</p>
            </div>
            <div class="col-lg-4 col-lg-offset-4 text-center">
                <a href="https://www.facebook.com/kpl.cse.iitb/?fref=ts"><img src="{% static 'img/Facebook-logo.png' %}" height="100px" width="170px"> </a>
                <a href="http://www.djangoproject.com/"><img src="https://www.djangoproject.com/m/img/badges/djangopowered126x54.gif" border="0" alt="Powered by Django." title="Powered by Django." /></a>
            </div>
        </div>
    </div>
</section>


<!-- jQuery -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static "vendor/jquery/jquery.easing.min.js" %}"></script>
<script src="{% static "vendor/scrollreveal/scrollreveal.min.js" %}"></script>
<script src="{% static "vendor/magnific-popup/jquery.magnific-popup.min.js" %}"></script>

<!-- Theme JavaScript -->
<script src="{% static "js/creative.js" %}"></script>
<script>
    function showTab(event) {
        var sourceParent = event.parentElement.parentElement;
        var sourceChilds = sourceParent.getElementsByClassName("rca-tab-content");
        var sourceLinkParent = sourceParent.getElementsByClassName("rca-tab-link");
        for (var i = 0; i < sourceChilds.length; i++) {
            sourceChilds.item(i).classList.remove("active");
        }
        for (var i = 0; i < sourceLinkParent.length; i++) {
            sourceLinkParent.item(i).classList.remove("active");
        }
        var dataTab = event.getAttribute("data-tab");

        event.classList.add("active");
        document.getElementById(dataTab).className += ' active';
    }
    function showTab2(event) {
        var sourceParent = event.parentElement.parentElement;
        var sourceChilds = sourceParent.getElementsByClassName("rca-tab-content");
        var sourceLinkParent = sourceParent.getElementsByClassName("rca-tab-link");
        for (var i = 0; i < sourceChilds.length; i++) {
            sourceChilds.item(i).classList.remove("active");
        }
        for (var i = 0; i < sourceLinkParent.length; i++) {
            sourceLinkParent.item(i).classList.remove("active");
        }
        var dataTab = event.getAttribute("data-tab");

        event.classList.add("active");
        document.getElementById(dataTab).className += ' active';
        document.getElementById(dataTab).style = 'display:initail;';
    }

</script>

</body>

</html>

templates/end_first_inning.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<section id="register">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center">
            <br>
            <br>
            <h3><b>End of First Inning</b></h3>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-offset-4 col-sm-4 col-xs-10 col-xs-offset-1 text-center">
             <p class="text-danger text-center">{{ error_message }}</p>
            <form id="register_form" method="post" action="" enctype="multipart/form-data">{% csrf_token %}

        </form>

        <button type="submit" form="register_form" value="Submit" class="btn btn-primary ">Next Inning</button>
        </div>

    </div>

</section>
{% endblock %}

templates/female_over.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<section id="register">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center">
            <br>
            <br>
            <h3><b>Female Over</b></h3>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-offset-4 col-sm-4 col-xs-10 col-xs-offset-1">
             <p class="text-danger text-center">{{ error_message }}</p>
            <form id="register_form" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
             {{ female_over_form|crispy }}

        </form>

        <button type="submit" form="register_form" value="Submit" class="btn btn-primary pull-right">Create</button>
        </div>

    </div>

</section>
{% endblock %}

templates/hit_wicket.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<section id="register">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 text-center">
            <br>
            <br>
            <h3><b>Hit Wicket</b></h3>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-offset-4 col-sm-4 col-xs-10 col-xs-offset-1">
             <p class="text-danger text-center">{{ error_message }}</p>
            <form id="register_form" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
             {{ hit_wicket_form|crispy }}

        </form>

        <button type="submit" form="register_form" value="Submit" class="btn btn-primary pull-right">Create</button>
        </div>

    </div>

</section>
{% endblock %}

templates/organizers.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<section id=organizers" style="background-color: white; ">
    <div class="container">
        <div class="row">
            <br>
            <br>
            <div class="col-lg-12 text-center">
                <h2 class="section-heading"><b>Our Amazing Team</b></h2>

            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/raj.jpg" width="170" height="170" class="img-responsive img-circle" alt="">
                    <h3><b>Raj</b></h3>
                    <p class="text-muted"><b>Organizer <br>& <br>Web Designer</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:8142533445</b></p>

                </div>
            </div>

            <div class="col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/pawan.jpg" width="150" height="150" class="img-responsive img-circle" alt="">
                    <h3><b>Pawan Chandurkar</b></h3>
                    <p class="text-muted"><b>Organizer <br>& <br>Sports Secy</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:8446996867</b></p>

                </div>
            </div>

            <div class="col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/jigar.jpg" width="145" height="130" class="img-responsive img-circle" alt="">
                    <h3><b>Jigar Mistry</b></h3>
                    <p class="text-muted"><b>Organizer</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:9967161795</b></p>

                </div>
            </div>
            </div>
        <div class="row">


            <div class="col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/sankalp.jpg" width="160" height="170" class="img-responsive img-circle" alt="">
                    <h3><b>Sankalp Rangare</b></h3>
                    <p class="text-muted"><b>Organizer</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:9405587948</b></p>

                </div>
            </div>

            <div class="col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/ajay.jpg" width="150" height="150" class="img-responsive img-circle" alt="">
                    <h3><b>Ajay Kedare</b></h3>
                    <p class="text-muted"><b>Organizer</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:8149599012</b></p>

                </div>
            </div>
            <div class="col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/aditya.jpg" width="150" height="150" class="img-responsive img-circle" alt="">
                    <h3><b>Aditya Samadhiya</b></h3>
                    <p class="text-muted"><b>Organizer</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:9650962038</b></p>

                </div>
            </div>
            <div class="col-sm-offset-4 col-sm-4">
                <div class="team-member">
                    <img src="{{ MEDIA_URL }}/kpl/media/player_pics/akshat.jpg" width="150" height="150" class="img-responsive img-circle" alt="">
                    <h3><b>Akshat Jaiswal</b></h3>
                    <p class="text-muted"><b>Organizer</b></p>
                    <p class="text-center text-muted" style="font-family: Arial;"><b>Phone:8989779509</b></p>

                </div>
            </div>

    </div>
        </div>
    </div>

</section>


{%  endblock %}

templates/schedule.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <section id=organizers" style="background-color: white; ">
        <div class="container">
            <div class="row">
                <br>
                <br>
                <div class="col-lg-12 text-center" style="border-bottom: thick solid black;">
                    <h2 class="section-heading"><b>Match Schedule</b></h2>

                </div>
            </div>
            <br>
            <div class="row">
                {% for match in matches %}
                    <div class="col-sm-12" style="padding-top: 10px;padding-bottom: 10px;border-bottom: thick solid black;">
                        <h3 class="section-heading text-center"><b>Match {{ match.match_number }}</b></h3>
                        <h5 class="section-heading text-center"><b>{{ match.date }}</b></h5>
                        <br>
                        <div class="col-sm-offset-2 col-sm-3 ">
                            <div class="team-match text-center">
                                <img src="{{ MEDIA_URL }}{{ match.team1.logo.url }}" style="width:250px;height: 250px;"
                                     class="img-responsive img-circle" alt="" width="50px">
                                <h3 ><a href="{% url 'teams:players' match.team1.id %}"><b>{{ match.team1.name }}</b></a></h3>
                            </div>
                        </div>
                        <div class="col-sm-3 col-sm-offset-2">
                            <div class="team-match text-center">
                                <img src="{{ MEDIA_URL }}{{ match.team2.logo.url }}" style="width:250px;height: 250px;"
                                     class="img-responsive img-circle" alt="">
                                <h3><a href="{% url 'teams:players' match.team2.id %}"><b>{{ match.team2.name }}</b></a></h3>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>

    </section>


{% endblock %}